[package]
name = "pocket-tui-napi"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
libc.workspace = true
napi.workspace = true
napi-derive.workspace = true
pocket-tui-core = { path = "../pocket-tui-core" }
pocket-tui-terminal = { path = "../pocket-tui-terminal" }

[build-dependencies]
napi-build = "2"
