import type { EntitySeed, LevelDefinition, Noun, Word } from "./engine.js";

function object(id: string, noun: Noun, x: number, y: number): EntitySeed {
  return { id, kind: "object", noun, x, y };
}

function text(id: string, word: Word, x: number, y: number): EntitySeed {
  return { id, kind: "text", word, x, y };
}

/** Five original, deterministic teaching boards for the Rule Shift demo. */
export const RULE_SHIFT_LEVELS: readonly LevelDefinition[] = [
  {
    id: "kindle",
    title: "01 / KINDLE",
    hint: "Push one word north. Then let the mote find its goal.",
    width: 11,
    height: 7,
    entities: [
      text("kindle-mote", "MOTE", 1, 1),
      text("kindle-is-you", "IS", 2, 1),
      text("kindle-you", "YOU", 3, 1),
      text("kindle-goal", "GOAL", 6, 1),
      text("kindle-is-win", "IS", 7, 1),
      text("kindle-win", "WIN", 8, 2),
      object("kindle-player", "MOTE", 8, 3),
      object("kindle-target", "GOAL", 4, 4),
    ],
  },
  {
    id: "breakwater",
    title: "02 / BREAKWATER",
    hint: "A sentence can be a lock. Push its last word out of tune.",
    width: 13,
    height: 8,
    entities: [
      text("break-wall", "WALL", 1, 2),
      text("break-is-stop", "IS", 2, 2),
      text("break-stop", "STOP", 3, 2),
      text("break-mote", "MOTE", 5, 1),
      text("break-is-you", "IS", 6, 1),
      text("break-you", "YOU", 7, 1),
      text("break-goal", "GOAL", 8, 6),
      text("break-is-win", "IS", 9, 6),
      text("break-win", "WIN", 10, 6),
      object("break-player", "MOTE", 3, 4),
      object("break-target", "GOAL", 9, 4),
      object("break-wall-2", "WALL", 6, 2),
      object("break-wall-3", "WALL", 6, 3),
      object("break-wall-4", "WALL", 6, 4),
      object("break-wall-5", "WALL", 6, 5),
    ],
  },
  {
    id: "freight",
    title: "03 / FREIGHT",
    hint: "The corridor answers only when the whole chain moves.",
    width: 13,
    height: 7,
    entities: [
      text("freight-mote", "MOTE", 1, 1),
      text("freight-is-you", "IS", 2, 1),
      text("freight-you", "YOU", 3, 1),
      text("freight-crate", "CRATE", 5, 1),
      text("freight-is-push", "IS", 6, 1),
      text("freight-push", "PUSH", 7, 1),
      text("freight-goal", "GOAL", 8, 5),
      text("freight-is-win", "IS", 9, 5),
      text("freight-win", "WIN", 10, 5),
      object("freight-player", "MOTE", 2, 3),
      object("freight-crate-a", "CRATE", 4, 3),
      object("freight-crate-b", "CRATE", 5, 3),
      object("freight-target", "GOAL", 9, 3),
    ],
  },
  {
    id: "twin-current",
    title: "04 / TWIN CURRENT",
    hint: "One command, two signals. A wall may stop one but not the other.",
    width: 12,
    height: 9,
    entities: [
      text("twin-mote", "MOTE", 1, 1),
      text("twin-is-mote-you", "IS", 2, 1),
      text("twin-mote-you", "YOU", 3, 1),
      text("twin-orb", "ORB", 5, 1),
      text("twin-is-orb-you", "IS", 6, 1),
      text("twin-orb-you", "YOU", 7, 1),
      text("twin-wall", "WALL", 9, 1),
      text("twin-is-wall-stop", "IS", 9, 2),
      text("twin-wall-stop", "STOP", 9, 3),
      text("twin-goal", "GOAL", 7, 7),
      text("twin-is-goal-win", "IS", 8, 7),
      text("twin-goal-win", "WIN", 9, 7),
      object("twin-mote-object", "MOTE", 2, 4),
      object("twin-orb-object", "ORB", 2, 6),
      object("twin-blocker", "WALL", 4, 4),
      object("twin-target", "GOAL", 6, 6),
    ],
  },
  {
    id: "bloom",
    title: "05 / BLOOM",
    hint: "Complete the new name. The mote can change and still remain yours.",
    width: 12,
    height: 9,
    entities: [
      text("bloom-mote-you", "MOTE", 1, 1),
      text("bloom-is-mote-you", "IS", 2, 1),
      text("bloom-you", "YOU", 3, 1),
      text("bloom-goal", "GOAL", 7, 1),
      text("bloom-is-goal-win", "IS", 8, 1),
      text("bloom-win", "WIN", 9, 1),
      text("bloom-bloom", "BLOOM", 1, 7),
      text("bloom-is-bloom-you", "IS", 2, 7),
      text("bloom-bloom-you", "YOU", 3, 7),
      text("bloom-change-mote", "MOTE", 5, 3),
      text("bloom-change-is", "IS", 6, 3),
      text("bloom-change-word", "BLOOM", 7, 4),
      object("bloom-player", "MOTE", 7, 5),
      object("bloom-target", "GOAL", 3, 4),
    ],
  },
] as const;
