/** PocketTUI package version. */
export const version = "0.1.0";

export { CellBuffer, type CellBufferCell } from "./canvas.js";

export {
  BoxHandle,
  CanvasHandle,
  SceneHandle,
  TextHandle,
  TranscriptBlockHandle,
  TranscriptHandle,
  TuiApp,
  VirtualTranscriptHandle,
  createTui,
  type CreateTuiOptions,
  type CanvasPresentOptions,
  type EffectBusFrame,
  type FlushMode,
  type TuiAppState,
  type TuiInputEvent,
  type TuiMemoryStats,
  type TuiViewportSize,
} from "./app.js";
export {
  PTX_HEADER_BYTES,
  PTX_MAGIC,
  PTX_MAJOR_VERSION,
  PTX_MAX_PACKET_BYTES,
  PTX_OPERATION_HEADER_BYTES,
  PtxDecodeError,
  PtxOpcode,
  PtxPacketEncoder,
  canvasFrameRecordByteLength,
  canvasRowsRecordByteLength,
  decodePtx,
  type BoxDirection,
  type BoxPacketOptions,
  type CanvasFrame,
  type CanvasRowReplacement,
  type CanvasRowRun,
  type CanvasRowsPatch,
  type CanvasRun,
  type CursorPacketOptions,
  type CursorShape,
  type EffectBusChannel,
  type EffectBusPacketOptions,
  type EffectBusProfile,
  type DecodedPtxOperation,
  type DecodedPtxPacket,
  type TuiColor,
  type TuiStyle,
} from "./protocol.js";
export {
  NATIVE_PROTOCOL_FEATURE_CANVAS_ROWS,
  loadNativeBinding,
  type NativeBinding,
  type NativeInputEvent,
  type NativeMemoryStats,
  type NativeTuiSession,
  type NativeViewportSize,
} from "./native.js";
